---
title: "About this Workshop"
---

[Link to session page.](https://onlinelearningconsortium.org/olc-accelerate-2019-session-page/?session=7732)

# BRIEF ABSTRACT
Are you an impostor? Full of doubt, inadequacy? Do you think your success is just luck? These feelings lead to a destructive mindset of stress, hesitancy, and disengagement.  Together, we'll learn how to recognize and address the impostor phenomenon and how to flip the script on your own “impostor” dialogues.

# EXTENDED ABSTRACT
While attending OLC Innovate 2018, a graduate student standing at the back of the room noted that she didn’t belong at the conference. It was not because of the conference topics or structure. It was because she felt like she was somehow not as knowledgeable as or not as experienced as other attendees.  This student, working on her doctorate in online learning belonged at the conference, and yet she felt her experiences and accomplishments in the online learning landscape were somehow not adequate to even be in the same room with other attendees.

Philosopher Bertrand Russell wrote: “The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.”  This doubt that Russell speaks of can sometimes be positive, offering an opportunity to learn, grow, and develop.  But sometimes this doubt can be destructive, suggesting to our innermost selves that we aren’t good enough, smart enough, or able to accomplish what is  in front of us. This is likely what the graduate student was feeling.

This type of “self-doubt” is sometimes referred to as the Impostor Phenomenon, which some research estimates almost 70% of successful people have experienced (Gravoy, 2007).  Impostor phenomenon (IP) is a “psychological pattern. It is based on intense, secret feelings of fraudulence in the face of success and achievement. If you suffer from the impostor phenomenon, you believe that you don’t deserve your success; you’re a phony who has somehow ‘gotten away with it.” (Harvey & Katz, 1984, p. 3).  Similarly, Tabaka (2018) described impostor phenomenon as, “When in the throes of an Imposter Syndrome struggle, you may feel that you're the only person in your circle (or in the whole world) who suffers from this level of self-doubt. In those moments, you're certain that every label you've assigned to yourself, including inadequate, incompetent, undeserving, unqualified, fake, and unequivocal failure is absolutely accurate. The pain associated with the Imposter Syndrome is very real, but the self-assessment that put you there is not” (p. 1). 

As online leaders, designers, faculty, and support professionals, the impostor phenomenon can be a destructive force, one that can stymie our thinking in ways that shortchange any accomplishments, knowledge, or experiences that got us to the point we are at today.  As online teachers, experts, leaders, designers, or support professionals, addressing feelings in the impostor phenomenon are critical to our professional performance (Cozarelli & Major, 1990).

The purpose of this workshop is to start a conversation about the impostor phenomenon feelings that online teaching and learning professionals may experience and discuss strategies to address those feelings.  In this honest, personal, informative, and engaged express workshop, participants will explore the impostor phenomenon as it applies to their roles as online teachers, leaders, designers, and support professionals and how they might recover a sense of confidence in the work they do. Through a series of individual and small group activities, including the wall of confidence, writing positive mantras, and the values exercise, participants will be engaged in reflecting on the impostor phenomenon and creating a plan for flipping the impostor script.

By participating in this session, you will...

+ Self-assess your own impostor phenomenon level
+ Identify strategies for rewriting your own “impostor” dialogue.
+ Identify at least one person you will actively build a network with to further support and mentor one another within the structure and format that best supports you professional and academic growth.  

# REFERENCES
Cozzarelli, C., & Major, B. (1990). Exploring the validity of the impostor phenomenon. Journal of Social and Clinical Psychology, 9(4), 401-417.  
Gravois, John. (2007). You're Not Fooling Anyone. The Chronicle of Higher Education, 54(11), A1 A32-A32.  
Harvey, J.C. & Katz, C. (1984). If I’m So Successful, Why do I Feel Like A Fake? Random House: New York.  
Tabaka, M. (2018). Here's What Famous High Achievers Are Doing to Conquer Symptoms of the Imposter Syndrome.   Retrieved from https://www.inc.com/marla-tabaka/famous-high-achievers-are-finally-talki...
